export const siteData = {
  main: {
    hero: {
      title: "GROW YOUR\nWEALTH WITH\nINVESTO GROW",
      description: "Noida's premier real estate consultants specializing in high-yield commercial and retail investments. We guide you to the most profitable opportunities in the NCR region.",
      stats: [
        { value: "500", prefix: "", suffix: "+", label: "Properties Sold" },
        { value: "150", prefix: "", suffix: "+", label: "Happy Investors" },
        { value: "100Cr", prefix: "₹", suffix: "+", label: "Project Value" }
      ],
      agentsBadge: {
        avatars: ["/images/SandeepSingh.png", "/images/VikasRohen.png", "/images/RitikaRaghav.png", "/images/MahimaKumari.png"],
        text: "10+ Expert Advisors",
        rating: "4.9 / 5"
      }
    },
    about: {
      founder: {
        heading: "About the\nFounder",
        paragraphs: [
          'At the heart of Investo Grow is the vision and expertise of its founder, Nitin Jain, a seasoned professional with over 25 years of sales experience and 6 years of dedicated expertise in the real estate sector.',
          'Nitin’s journey into real estate began with his own investments. Through firsthand experience, he recognized the immense potential this sector holds for wealth creation when approached with the right strategy and guidance.',
          'Investo Grow was founded in 2026 with a mission to simplify real estate investments and make them accessible, transparent, and rewarding for Indian investors and NRIs alike.',
          'With a strong foundation in sales and a deep understanding of market dynamics, Nitin brings a client-first approach, ensuring every investor receives trustworthy advice and value-driven opportunities.'
        ],
        image: "/images/nitinji.png"
      },
      visionMission: [
        {
          title: "Our Vision",
          description: "At Investo Grow, our vision is to make Indian real estate investments safe, secure, and truly rewarding. We aim to help individuals grow their wealth while giving them complete peace of mind.",
          extraDescription: "We believe that every investment should add significant value to your portfolio and bring you closer to your financial goals.",
          icon: "Eye"
        },
        {
          title: "What Drives Us",
          description: "For us, it’s not just about properties—it’s about people. We are passionate about helping individuals turn their dreams into reality. Whether it’s a high-street shop or a corporate office, our success lies in yours.",
          extraDescription: "At Investo Grow, your growth is our purpose.",
          icon: "Heart"
        }
      ],
      whyInvest: {
        title: "Why Invest With Us",
        items: [
          { title: "Noida's Booming Market", description: "Noida is rapidly emerging as India's top real estate destination, offering immense potential for both commercial and retail growth. It's the perfect place to invest and grow.", icon: "TrendingUp" },
          { title: "Transparent Direct Deals", description: "Seamless experience by eliminating intermediaries. We build trust by ensuring you get the absolute best direct-from-developer value.", icon: "Users" },
          { title: "Detailed Analytics", description: "Honesty is core. From ROI projections to RERA compliance and detailed documentation, we maintain full transparency.", icon: "Eye" },
          { title: "Continuous Support", description: "Our relationship doesn’t end with a signature. We provide consistent follow-ups and management support to ensure a hassle-free experience.", icon: "CheckCircle2" }
        ]
      },
      benefits: {
        title: "Benefits of Commercial Real Estate",
        items: [
          { title: "High Rental Yields", description: "Earn stable income through commercial rental yields while benefiting from long-term capital appreciation in prime sectors.", icon: "TrendingUp" },
          { title: "Secure Asset Class", description: "Real estate remains India's most trusted asset class. We prioritize opportunities that ensure your capital stays safe and grows.", icon: "ShieldCheck" }
        ]
      }
    },
    services: {
      title: "Premier Commercial Solutions",
      subtitle: "Our specialized services focus on high-traffic retail spaces, grade-A corporate offices, and premium food court investments.",
      items: [
        { id: "01", title: "Corporate Offices", description: "Grade-A office suites in Noida's emerging IT hubs, designed for modern enterprises and high-yield returns.", image: "/images/commercial_office_noida.png" },
        { id: "02", title: "Retail Boulevards", description: "High-exposure retail shops in high-footfall locations, ensuring maximum visibility and consistent rental income.", image: "/images/CbmkqNbxGqLIF6f8HhhLjAtITV8.jpg" },
        { id: "03", title: "Dining & Leisure", description: "Premium food courts and entertainment zones in self-contained commercial ecosystems like GYGY FIVEO.", image: "/images/MNaTdWhKQ4PCxwtMgQRe9ROUJoe510.jpg" }
      ]
    },
    agents: {
      title: "Expert Guidance,\nProven ROI",
      description: "Our dedicated team of advisors specializes in the Noida commercial market, ensuring you make informed and profitable investment decisions.",
      items: [
        { name: "Sandeep Singh", role: "Sales Team Head (7 Years Exp)", image: "/images/SandeepSingh.png" },
        { name: "Vikas Rohen", role: "Sales Team Head (12 Years Exp)", image: "/images/VikasRohen.png" },
        { name: "Pravesh Tawar", role: "Sale Team Leader (3 Years Exp)", image: "/images/PraveshTawar.png" },
        { name: "Ritika Raghav", role: "Sales Manager (2.5 Years Exp)", image: "/images/RitikaRaghav.png" },
        { name: "Shivam Sharma", role: "Senior Sales Manager (2.5 Years Exp)", image: "/images/ShivamSharma.png" },
        { name: "Sahil Singh", role: "Sales Manager (2.5 Years Exp)", image: "/images/SahilSingh.png" },
        { name: "Bhawana Pal", role: "Senior Sales Executive (2 Years Exp)", image: "/images/BhawanaPal.png" },
        { name: "Mahima Kumari", role: "HR Manager (2 Years Exp)", image: "/images/MahimaKumari.png" },
        { name: "Rahman", role: "Sales Executive (6 Months Exp)", image: "/images/Rahman.png" }
      ]
    },
    testimonials: {
      tag: "Investor Success Stories",
      title: "TRUSTED BY MANY,\nLOVED BY ALL",
      description: "Our clients' success stories reflect our commitment to excellence. See how we've helped them secure their future with smart commercial investments.",
      items: [
        { name: "Ananya Sharma", role: "Tech Entrepreneur", image: "/images/1bXCvUXCPLThMThkksjOy63PM.jpg", text: "Investo Grow helped me secure a premium office suite at GYGY Mentis. Their transparency and ROI projections were spot on. Highly recommended!", rating: 5 },
        { name: "Deepika Reddy", role: "Retail Investor", image: "/images/dbWDZuR15FVj9cDN2ngoxogWU.jpg", text: "The team simplified the entire process of investing in a high-street shop. I was worried about the paperwork, but Nitin and his team handled everything.", rating: 5 },
        { name: "Rohan Malhotra", role: "Business Owner", image: "/images/h3b8XxI71wHeNvHUg0wtR8NAE.jpg", text: "Finding the right commercial spot in Noida can be a nightmare, but Sahil made it effortless. The 3rd-floor shop at FIVEO is already seeing great interest.", rating: 5 },
        { name: "Priya Iyer", role: "Finance Professional", image: "/images/YgD80vVXRZoLGwTr5ZaspUEKk.jpg", text: "Strategic advice and excellent follow-up. They don't just sell; they ensure your investment is managed well. Truly the best in Noida.", rating: 5 }
      ]
    },
    faq: {
      tag: "Help Center",
      title: "FREQUENTLY ASKED\nQUESTIONS",
      items: [
        { question: "What are the benefits of investing in Noida commercial property?", answer: "Noida offers high capital appreciation, rapid infrastructure growth (like the new Airport), and strong rental yields from IT and corporate firms." },
        { question: "Is GYGY Mentis RERA registered?", answer: "Yes, GYGY Mentis is fully RERA registered (UPRERAPRJ251909), ensuring complete legal safety and transparency for all investors." },
        { question: "What is the expected ROI on GYGY FIVEO?", answer: "Investors can expect significant capital appreciation (up to 25% in the first year) plus stable rental yields from the high-footfall high-street concept." },
        { question: "How safe is my investment with Investo Grow?", answer: "We exclusively deal with zero-debt developers with clear titles and a track record of timely delivery, ensuring your capital is protected." }
      ]
    },
    contact: {
      image: "/images/MNaTdWhKQ4PCxwtMgQRe9ROUJoe510.jpg",
      title: "Kickstart Your Profitable Property Journey",
      description: "Ready to invest in Noida's growth story? Whether it's a retail shop or a corporate suite, our experts are here to guide you toward maximum returns.",
      formFields: {
        firstName: "First Name",
        lastName: "Last Name",
        email: "Email Address",
        phone: "Phone Number",
        message: "Tell us about your investment goals...",
        button: "Schedule a Consultation"
      }
    },
    mainProperties: {
      title: "Premier Commercial Opportunities",
      items: [
        {
          id: "mentis-office-suites",
          image: "/images/commercial_office_noida.png",
          imageSecondary: "/images/RLD7TAwuETk2t51mW9hcW3YZu6816b1.jpg",
          status: "For Sale",
          location: "Sector 140, Noida",
          title: "GYGY Mentis Premium Office Suites",
          beds: "15",
          bedsLabel: "Suites",
          baths: "4",
          bathsLabel: "Units",
          sqft: 1500,
          price: "50 Lakhs onwards",
          possession: "Near Possession",
          developer: "GYGY Group",
          description: "GYGY Mentis Office Suites in Sector-140, Noida, are designed for high-end IT and corporate operations. With its 'Oculus' concept dining and state-of-the-art infrastructure, it offers a 12% assured rental and 25% capital appreciation potential.",
          highlights: ["Grade-A corporate office suites", "12% Assured Rental yield", "Super Structure already ready", "Direct Metro Station (Sec 142) connectivity"],
          amenities: ["Oculus Concept Dining", "High-Speed Business Internet", "24/7 Power & Security", "Workout & Fitness Gym", "Elite Business Hub", "Meeting Rooms"],
        },
        {
          id: "fiveo-high-street",
          image: "/images/CbmkqNbxGqLIF6f8HhhLjAtITV8.jpg",
          imageSecondary: "/images/yzpRxn2HI5TBopZVeE1K1WuVAd75d.jpg",
          status: "For Investment",
          location: "Sector 50, Noida",
          title: "GYGY FIVEO High Street Retail",
          beds: "45",
          bedsLabel: "Shops",
          baths: "3",
          bathsLabel: "Ground Floors",
          sqft: 2000,
          price: "1.5 Cr onwards",
          possession: "Dec 2026",
          developer: "GYGY Group",
          description: "Noida's first-ever high street with 3 ground floors. Nestled in Sector 50, surrounded by 12,000+ elite families, GYGY FIVEO is the ultimate hub for premium retail brands and extraordinary shopping experiences.",
          highlights: ["Unique 3-Ground-Floor Architecture", "Zero Debt Developer Company", "Sector 50 Elite Catchment Area", "High footfall & yield guarantee"],
          amenities: ["Fully Air-Conditioned", "High-Speed Elevators", "Ample Multi-Level Parking", "Lush Green Landscaping", "Outdoor Seating Area", "Fire Safety System"],
        },
        {
          id: "mentis-retail-blvd",
          image: "/images/CbmkqNbxGqLIF6f8HhhLjAtITV8.jpg",
          imageSecondary: "/images/RLD7TAwuETk2t51mW9hcW3YZu6816b1.jpg",
          status: "For Sale",
          location: "Sector 140, Noida",
          title: "Mentis Retail Boulevard",
          beds: "22",
          bedsLabel: "Shops",
          baths: "12",
          bathsLabel: "Plots/Blocks",
          sqft: 800,
          price: "75 Lakhs onwards",
          possession: "Near Possession",
          developer: "GYGY Group",
          description: "High-street retail shops at the heart of Noida's commercial sector. Surrounded by massive residential developments, these retail outlets ensure consistent daily footfall and early-entry ROI advantages.",
          highlights: ["Massive exposure for retail brands", "Direct Metro connectivity", "Near upcoming Noida International Airport", "Super structure complete"],
          amenities: ["Spacious Frontage", "Sitting Alcoves", "Centralized AC", "24/7 Security & Surveillance", "Resting Zones", "Food Court Access"],
        },
        {
          id: "fiveo-food-court",
          image: "/images/MNaTdWhKQ4PCxwtMgQRe9ROUJoe510.jpg",
          imageSecondary: "/images/qLilEwH5SGNsGXKkBeJk4iACc.jpg",
          status: "For Investment",
          location: "Sector 50, Noida",
          title: "FIVEO Premium Food Court",
          beds: "12",
          bedsLabel: "Stalls",
          baths: "1",
          bathsLabel: "Elite Dining Floor",
          sqft: 1500,
          price: "95 Lakhs onwards",
          possession: "Dec 2026",
          developer: "GYGY Group",
          description: "The ultimate destination for food enthusiasts. The FIVEO Food Court combines opulent retail experiences with exquisite dining, creating a luxury atmosphere that guarantees repeat visits.",
          highlights: ["Premium food & beverage brands", "Integrated with high-street retail", "Serving 12,000+ elite families", "Secure investment with high returns"],
          amenities: ["Centralized Cafeteria Space", "Exquisite Internal Lighting", "Common Seating Area", "High-Speed Internet", "Power Backup", "24/7 Security"],
        },
        {
          id: "mentis-corporate-hub",
          image: "/images/commercial_office_noida.png",
          imageSecondary: "/images/RLD7TAwuETk2t51mW9hcW3YZu6816b1.jpg",
          status: "For Sale",
          location: "Sector 140, Noida",
          title: "Mentis Corporate Wing Hub",
          beds: "10",
          bedsLabel: "Floors",
          baths: "1",
          bathsLabel: "Corporate Wing",
          sqft: 5000,
          price: "2.5 Cr onwards",
          possession: "Dec 2024",
          developer: "GYGY Group",
          description: "A marquee destination for large IT and electronic enterprises. Providing Grade-A office facilities with progressive infrastructure designed for future-ready global corporations.",
          highlights: ["Tallest skyrise in Sector 140", "Designed for Fortune 500 standards", "Clean roadways & high-speed connectivity", "State-of-the-art HVAC systems"],
          amenities: ["Conference & Event Centre", "Private Roof Terrace", "Gymnasium & Spa", "Executive Lounge", "Helipad Access", "Valet Parking"],
        },
        {
          id: "fiveo-luxury-boutiques",
          image: "/images/CbmkqNbxGqLIF6f8HhhLjAtITV8.jpg",
          imageSecondary: "/images/yzpRxn2HI5TBopZVeE1K1WuVAd75d.jpg",
          status: "For Sale",
          location: "Sector 50, Noida",
          title: "FIVEO Luxury Boutiques",
          beds: "18",
          bedsLabel: "Showrooms",
          baths: "3",
          bathsLabel: "Luxury Levels",
          sqft: 3200,
          price: "2.8 Cr onwards",
          possession: "Dec 2026",
          developer: "GYGY Group",
          description: "FIVEO Luxury Boutiques offer an opulent retail environment for the sophisticated shopper. Prime location in Sector 50, transforming the retail experience for the most premium global brands.",
          highlights: ["Tailored for luxury fashion & jewels", "Exquisite architectural design", "Double-height shop fronts", "Massive branding visibility"],
          amenities: ["VIP Lounge Access", "Dedicated Loading Bay", "Personalized Concierge", "Premium Landscaping", "Climate Controlled Mall", "Surveillance Centre"],
        },
        {
          id: "mentis-oculus-dining",
          image: "/images/MNaTdWhKQ4PCxwtMgQRe9ROUJoe510.jpg",
          imageSecondary: "/images/qLilEwH5SGNsGXKkBeJk4iACc.jpg",
          status: "For Investment",
          location: "Sector 140, Noida",
          title: "Oculus Premium Dining Zone",
          beds: "8",
          bedsLabel: "Levels",
          baths: "12",
          bathsLabel: "Elite Penthouses",
          sqft: 3500,
          price: "1.2 Cr onwards",
          possession: "Near Possession",
          developer: "GYGY Group",
          description: "The Oculus Concept at GYGY Mentis introduces an exclusive restaurant and networking hub. Combining upscale dining with elite corporate hospitality for Noida's top professionals.",
          highlights: ["Noida's first Oculus Concept hub", "High-yield F&B investment", "Skyline views of Expressway", "Private elevator access"],
          amenities: ["Rooftop Bar & Grill", "Meeting Spots", "Valet Service", "Luxury Interiors", "Live Music Stage", "Cigar Lounge"],
        },
        {
          id: "fiveo-fun-zone",
          image: "/images/CbmkqNbxGqLIF6f8HhhLjAtITV8.jpg",
          imageSecondary: "/images/qLilEwH5SGNsGXKkBeJk4iACc.jpg",
          status: "For Investment",
          location: "Sector 50, Noida",
          title: "FIVEO Fun & Leisure Zone",
          beds: "22",
          bedsLabel: "Zones",
          baths: "5",
          bathsLabel: "Play Areas",
          sqft: 5000,
          price: "80 Lakhs onwards",
          possession: "Dec 2026",
          developer: "GYGY Group",
          description: "An entertainment hub built for families and kids. A unique dimension of 'Play' within a high-street environment, adding consistent footfall and repeat visits for all investors.",
          highlights: ["Noida Sector 50 primary fun hub", "Carefree experiential zones", "Designed for massive crowd pull", "Integrated with food court"],
          amenities: ["Indoor Play Area", "Gaming Zone", "Ample Outdoor Seating", "Parents Waiting Lounge", "Safety-First Design", "Backup Power"],
        }
      ]
    },
    ongoingProjects: {
      title: "Ongoing Projects",
      subtitle: "Under Construction",
      items: [
        {
          id: "verdant-heights",
          image: "/images/RQA2wDd4pBGiWeZ2ktDtcszRbrM.jpg",
          imageSecondary: "/images/yzpRxn2HI5TBopZVeE1K1WuVAd75d.jpg",
          title: "Verdant Heights",
          category: "Luxury Residential",
          location: "Sector 150, Noida",
          developer: "Investo Grow Premier",
          completion: "Dec 2025",
          progress: 78,
          units: "240 Units",
          priceRange: "₹1.2 Cr – ₹3.8 Cr",
          rera: "UPRERAPRJ112233",
          status: "Under Construction",
          description: "Verdant Heights is a landmark luxury residential tower rising above Sector 150, Noida — the city's most sought-after green sector. Offering sweeping views of the Yamuna biodiversity park, each apartment is designed for those who demand both nature and urban convenience.",
          highlights: ["78% construction complete", "RERA registered & compliant", "Yamuna park-facing units", "Earthquake-resistant RCC frame", "EV charging in every parking"],
          amenities: ["Infinity-edge clubhouse pool", "Rooftop terrace garden", "Co-working lounge", "Jogging & cycle track", "Children's adventure park", "24/7 gated security"],
        },
        {
          id: "serenity-villas",
          image: "/images/BVa676Qcx73rJphRua2dXkWNAs.jpg",
          imageSecondary: "/images/IAU2BSodEZAzSqJjl5B2xm2bys849e.jpg",
          title: "Serenity Villas",
          category: "Premium Villas",
          location: "Sector 128, Noida",
          developer: "Investo Grow Premier",
          completion: "Mar 2026",
          progress: 55,
          units: "48 Villas",
          priceRange: "₹4.5 Cr – ₹7.2 Cr",
          rera: "UPRERAPRJ445566",
          status: "Under Construction",
          description: "Serenity Villas is an exclusive enclave of 48 independent villas adjacent to the Noida Golf Course. Each villa is a 4-bedroom, G+2 structure with a private garden, rooftop terrace, and plunge pool, offering the rarest combination of space and prestige in Noida.",
          highlights: ["Golf course-adjacent location", "Private plunge pool per villa", "Double-height living rooms", "Top-tier German kitchen fittings", "100% solar-powered common areas"],
          amenities: ["Private plunge pool", "4-car basement parking", "Rooftop terrace per villa", "On-site concierge desk", "Landscaped central boulevard", "Private kids' club"],
        },
        {
          id: "the-apex-towers",
          image: "/images/RQA2wDd4pBGiWeZ2ktDtcszRbrM.jpg",
          imageSecondary: "/images/yzpRxn2HI5TBopZVeE1K1WuVAd75d.jpg",
          title: "The Apex Towers",
          category: "Ultra Luxury",
          location: "Sector 94, Noida",
          developer: "Investo Grow Premier",
          completion: "Jun 2026",
          progress: 42,
          units: "120 Units",
          priceRange: "₹2.8 Cr – ₹9.5 Cr",
          rera: "UPRERAPRJ778899",
          status: "Launching Soon",
          description: "The Apex Towers will become the tallest residential landmark in Noida's Sector 94 — commanding panoramic views of Delhi, the Okhla Bird Sanctuary, and the Yamuna river. With only 120 exclusive units spread across 42 floors, it is a true collector's-edition address.",
          highlights: ["42-floor skyrise — tallest in sector", "Only 3 units per floor", "Panoramic Yamuna & Delhi views", "Air filtration system on every floor", "Concierge-managed smart home"],
          amenities: ["Sky lounge at 40th floor", "Private cigar & wine lounge", "Olympic lap pool", "Virtual golf simulator", "Helipad on terrace", "Butler & housekeeping service"],
        },
        {
          id: "greenfield-square",
          image: "/images/CbmkqNbxGqLIF6f8HhhLjAtITV8.jpg",
          imageSecondary: "/images/RLD7TAwuETk2t51mW9hcW3YZu6816b1.jpg",
          title: "Greenfield Square",
          category: "Commercial & Mixed-Use",
          location: "Sector 62, Noida",
          developer: "Investo Grow Commercial",
          completion: "Sep 2026",
          progress: 35,
          units: "200,000 sqft",
          priceRange: "₹80 L – ₹5 Cr",
          rera: "UPRERAPRJ990011",
          status: "Under Construction",
          description: "Greenfield Square is Noida's most anticipated mixed-use commercial destination in Sector 62 — the IT hub of the NCR. Spanning 200,000 sqft across 18 floors, it offers Grade-A office spaces, premium retail on ground & first floors, and serviced business suites.",
          highlights: ["Grade-A office specifications", "200,000 sqft mixed-use complex", "Metro-adjacent (Sector 62 Blue Line)", "9.5% guaranteed rental return", "IGBC Green-certified building"],
          amenities: ["Rooftop amphitheatre & café", "Multi-level parking for 800 cars", "Food court & fine dining floor", "Concierge & business centre", "Conference & event spaces", "24/7 facility management"],
        },
      ]
    }
  },
  nri: {
    hero: {
      badge: "Exclusive NRI Portfolio",
      title: "Invest in India's Growth Story with",
      titleHighlight: "Absolute Confidence",
      description: "Curated premium real estate opportunities in Noida, exclusively for Non-Resident Indians. Experience end-to-end support, zero middlemen, and maximum returns.",
      image: "/images/Ho6IwoNLhdp9kCvS3CqnIvb0.jpg"
    },
    about: {
      commitment: {
        subtitle: "Our Commitment",
        title: "Dedicated to Your Financial Growth Offshore",
        paragraphs: [
          "For NRIs, managing investments in India can often seem challenging due to distance and administrative hurdles. We exist to bridge that gap. Investo Grow was founded to make investments safe, secure, and truly rewarding, giving you complete peace of mind.",
          "Led by Nitin Jain, a visionary with over 25 years of experience, we provide value-driven real estate opportunities. We ensure that every investment adds significant value to your portfolio securely with complete transparency."
        ],
        image: "/images/Ho6IwoNLhdp9kCvS3CqnIvb0.jpg"
      },
      whyChooseUs: {
        subtitle: "Trust & Excellence",
        title: "Why NRIs Choose Us",
        items: [
          { title: "100% Secure & Reliable", description: "Your money is safe. We prioritize opportunities that ensure capital protection and long-term secure growth in reliable asset classes.", icon: "ShieldCheck" },
          { title: "Dual Income Advantage", description: "Earn consistent rental yields while benefiting from massive property appreciation in Noida's booming real estate market.", icon: "TrendingUp" },
          { title: "No Middlemen", description: "We facilitate direct deals, eliminating unnecessary intermediaries to build trust and ensure you get the absolute best value.", icon: "Users" },
          { title: "End-to-End Support", description: "From initial selection to documentation and ongoing property management, we handle everything locally so you don't have to.", icon: "CheckCircle" }
        ]
      }
    },
    properties: [
      {
        id: "prop-1",
        image: "/images/RQA2wDd4pBGiWeZ2ktDtcszRbrM.jpg",
        imageSecondary: "/images/yzpRxn2HI5TBopZVeE1K1WuVAd75d.jpg",
        title: "Gold Coast Penthouse",
        location: "Sector 150, Noida",
        price: "₹7.5 Cr",
        beds: 4,
        bedsLabel: "Beds",
        baths: 4,
        bathsLabel: "Baths",
        sqft: 4500,
        badge: "Premium",
        roi: "+22% ROI",
        category: "Ultra Luxury",
        status: "Ready to Move",
        possession: "Immediate",
        developer: "Supertech Group",
        description: "Gold Coast Penthouse is the crown jewel of Sector 150, Noida — a sprawling 4-bedroom sky estate offering sweeping views of the Noida skyline and the Yamuna biodiversity park. Every inch is designed to reflect the tastes of a global traveller who calls India home.",
        highlights: ["Panoramic city & park views", "Private rooftop terrace", "Italian marble flooring throughout", "Smart home with Alexa integration", "3 dedicated car parking spots"],
        amenities: ["Infinity rooftop pool", "24/7 concierge & valet", "Club house & fine dining", "Electric vehicle charging bay", "Helipad access (tower)", "Spa & wellness centre"],
        rera: "UPRERAPRJ123456",
      },
      {
        id: "prop-2",
        image: "/images/BVa676Qcx73rJphRua2dXkWNAs.jpg",
        imageSecondary: "/images/IAU2BSodEZAzSqJjl5B2xm2bys849e.jpg",
        title: "The Imperial Villas",
        location: "Sector 143, Noida",
        price: "₹5.2 Cr",
        beds: 3,
        bedsLabel: "Beds",
        baths: 3,
        bathsLabel: "Baths",
        sqft: 3200,
        badge: "Hot Deal",
        roi: "+17% ROI",
        category: "Luxury Villa",
        status: "Under Construction",
        possession: "Dec 2026",
        developer: "Godrej Properties",
        description: "The Imperial Villas redefines premium township living in Sector 143 — strategically located minutes from the Expressway, Jewar Airport corridor, and top global schools. Each villa is an independent ground-plus-one structure with a private garden and plunge pool.",
        highlights: ["Independent G+1 villa structure", "Private garden & plunge pool", "German modular kitchen", "5-minute drive to Jewar Airport corridor", "Zero GST (RERA compliant ready)"],
        amenities: ["Clubhouse with 50+ amenities", "Jogging & cycle track", "24/7 gated security", "Community amphitheatre", "Co-working lounge", "Kids play & learning zone"],
        rera: "UPRERAPRJ654321",
      },
      {
        id: "prop-3",
        image: "/images/RQA2wDd4pBGiWeZ2ktDtcszRbrM.jpg",
        imageSecondary: "/images/yzpRxn2HI5TBopZVeE1K1WuVAd75d.jpg",
        title: "Skyline Residences",
        location: "Sector 128, Noida",
        price: "₹9.8 Cr",
        beds: 5,
        bedsLabel: "Beds",
        baths: 5,
        bathsLabel: "Baths",
        sqft: 6000,
        badge: "Ultra Luxury",
        roi: "+19% ROI",
        category: "Ultra Luxury",
        status: "Ready to Move",
        possession: "Immediate",
        developer: "DLF Limited",
        description: "Skyline Residences is Noida's most exclusive ultra-luxury address — a rare 5-bedroom duplex offering 6,000 sqft of curated living space across two floors. Located in the prestigious Sector 128, steps away from the Noida Golf Course, it is the ultimate symbol of arrival.",
        highlights: ["Duplex penthouse configuration", "Golf course & Yamuna river views", "Private lift lobby", "Home theatre & wine cellar", "Premium fittings: Kohler, Grohe, Häfele"],
        amenities: ["Olympic size swimming pool", "Private wine lounge", "Business centre & boardroom", "Pet park & grooming salon", "Yoga pavilion & meditation deck", "Rooftop observatory deck"],
        rera: "UPRERAPRJ789012",
      },
      {
        id: "mentis-office",
        image: "/images/commercial_office_noida.png",
        imageSecondary: "/images/RLD7TAwuETk2t51mW9hcW3YZu6816b1.jpg",
        status: "Under Construction",
        category: "Commercial",
        location: "Sector 140, Noida",
        title: "GYGY Mentis Office Suites",
        beds: "15",
        bedsLabel: "Suites",
        baths: "4",
        bathsLabel: "Units",
        price: "₹50 Lakhs",
        sqft: 1500,
        possession: "Near Possession",
        developer: "GYGY Group",
        description: "GYGY Mentis offers premium grade-A office suites in Sector-140, Noida. With an impressive 12% assured rental return and up to 25% capital appreciation in one year, it is the ultimate destination for smart investors.",
        highlights: ["Direct DMIC & FNG Expressway connectivity", "12% Assured Rental", "Upto 25% Capital Appreciation", "Near Metro Station Sector 142", "Super Structure Ready"],
        amenities: ["Workout & Fitness Gym", "Entertainment Zone", "High-Speed Internet", "Meeting Spaces", "Air-Conditioned", "24/7 Security"],
        rera: "UPRERAPRJ251909",
        badge: "Premium Investment",
        roi: "+25% Growth"
      },
      {
        id: "mentis-retail",
        title: "Mentis Retail Boulevard",
        price: "₹75 Lakhs",
        beds: "22",
        bedsLabel: "Shops",
        baths: "12",
        bathsLabel: "Plots/Blocks",
        sqft: 800,
        status: "Under Construction",
        category: "Commercial",
        location: "Sector 140, Noida",
        possession: "Near Possession",
        developer: "GYGY Group",
        description: "Positioned at the heart of Noida's commercial sector, Mentis Retail Boulevard provides unparalleled exposure. Surrounded by over 10 lakhs families, these high-street retail shops ensure massive daily footfall and great ROI.",
        highlights: ["High-street retail exposure", "10 Lakhs+ families nearby", "Direct Metro Station connectivity", "30 Min to Noida Airport"],
        amenities: ["Spacious Retail Shops", "Resting Sitting Alcove", "Ample Parking", "24/7 Security", "Central Air Conditioning"],
        image: "/images/CbmkqNbxGqLIF6f8HhhLjAtITV8.jpg",
        imageSecondary: "/images/RLD7TAwuETk2t51mW9hcW3YZu6816b1.jpg",
        rera: "UPRERAPRJ251909",
        badge: "High Footfall",
        roi: "12% Assured"
      },
      {
        id: "fiveo-high-street",
        title: "GYGY FIVEO High Street",
        price: "₹1.5 Cr",
        beds: "45",
        bedsLabel: "Shops",
        baths: "3",
        bathsLabel: "Ground Floors",
        sqft: 2000,
        status: "Under Construction",
        category: "Commercial",
        location: "Sector 50, Noida",
        possession: "2026",
        developer: "GYGY Group",
        description: "Experience Noida's first-ever high street with 3 ground floors at GYGY FIVEO. Nestled in Sector 50 among 12,000 elite families, it's crafted to meet luxury needs and provide extraordinary shopping experiences.",
        highlights: ["Noida's first 3 ground floors", "Sector 50 Elite Location", "Zero Debt Company Developer", "Highest footfall guarantee"],
        amenities: ["Fully Air-Conditioned", "High-Speed Elevators", "Ample Parking Space", "Lush Green Landscaping"],
        rera: "UPRERAPRJ662072",
        badge: "Exclusive Retail",
        roi: "High Yield",
        image: "/images/CbmkqNbxGqLIF6f8HhhLjAtITV8.jpg",
        imageSecondary: "/images/yzpRxn2HI5TBopZVeE1K1WuVAd75d.jpg"
      },
      {
        id: "fiveo-fun-zone",
        title: "FIVEO Fun & Leisure Zone",
        price: "₹80 Lakhs",
        beds: "22",
        bedsLabel: "Zones",
        baths: "5",
        bathsLabel: "Play Areas",
        sqft: 5000,
        status: "Under Construction",
        category: "Commercial",
        location: "Sector 50, Noida",
        possession: "2026",
        developer: "GYGY Group",
        description: "The Fun & Entertainment Zone at GYGY FIVEO is built to host joyful and spontaneous unfiltered moments. It introduces a third dimension of play to the city, adding consistent footfall and repeat visits for massive investor returns.",
        highlights: ["Premium Entertainment Hub", "Carefree experiential zones", "Designed for families and kids", "High consistent footfall"],
        amenities: ["Outdoor Seating Area", "Backup Power Supply", "Fire Safety & Sprinkler System", "Kids Zone"],
        rera: "UPRERAPRJ662072",
        badge: "Entertainment",
        roi: "15% ROI",
        image: "/images/CbmkqNbxGqLIF6f8HhhLjAtITV8.jpg",
        imageSecondary: "/images/qLilEwH5SGNsGXKkBeJk4iACc.jpg"
      }
    ]
  }
};
